export const BUTTON_CLICK = 'BUTTON_CLICK';
export const CLEAR_DISPLAY = 'CLEAR_DISPLAY';
export const BACKSPACE_DISPLAY = 'BACKSPACE_DISPLAY';
export const REPLACE_OPERATOR = 'REPLACE_OPERATOR';
export const SET_DOT_DECIMAL = 'SET_DOT_DECIMAL';
export const EVALUATE = 'EVALUATE';
